In [1]:
import numpy as np
from families import Gaussian, Bernoulli, Poisson
from glm import GLM

In [2]:
N = 100000
X = np.empty(shape=(N, 3))
X[:, 0] = 1.0
X[:, 1] = np.random.uniform(size=N)
X[:, 2] = np.random.uniform(size=N)
nu = 1 - 2*X[:, 1] + X[:, 2]

## Linear Model

In [3]:
y = nu + np.random.normal(size=N)
model = GLM(family=Gaussian())
model.fit(X, y)

In [4]:
model.coef_

array([ 1.01175585, -2.01266197,  0.98997601])

## Linear Model with Sample Weights

In [5]:
sample_weights = np.random.uniform(0, 2, size=N)

In [6]:
model = GLM(family=Gaussian())
model = model.fit(X, y, sample_weights=sample_weights)

In [7]:
model.coef_

array([ 1.00125653, -2.00780469,  1.00419945])

## Logistic Model

In [8]:
p = 1 / (1 + np.exp(-nu))
y_logistic = np.random.binomial(1, p=p, size=N)

In [9]:
model = GLM(family=Bernoulli())
model.fit(X, y_logistic)

In [10]:
model.coef_

array([ 0.99412135, -2.00376412,  1.00137171])

## Poission Model

In [11]:
mu = np.exp(nu)
y_poisson = np.random.poisson(lam=mu, size=N)

In [12]:
model = GLM(family=Poisson())
model.fit(X, y_poisson)

In [13]:
model.coef_

array([ 1.00256164, -2.00883683,  0.99978625])

## Poisson with Exposures

In [14]:
mu = np.exp(nu)
expos = np.random.uniform(0, 10, size=N)
y_poisson = np.random.poisson(lam=(mu*expos), size=N)

In [15]:
model = GLM(family=Poisson())
model.fit(X, y_poisson, offset=np.log(expos))

In [16]:
model.coef_

array([ 1.00048038, -1.99931543,  1.00103118])